import type {
  Stakeholder,
  Committee,
  RaciEntry,
  ApprovalRule,
  Request,
  CommunicationLogEntry,
  AuditEvent,
} from './types'

const now = new Date().toISOString()
const past = (d: number) => new Date(Date.now() - d * 86400000).toISOString()

export const MOCK_STAKEHOLDERS: Stakeholder[] = [
  {
    stakeholderId: 'SH-0001',
    displayName: 'Jane Smith',
    organization: 'Program Office',
    stakeholderType: 'Internal',
    discipline: 'Systems',
    roles: ['System Engineer', 'CCB Member'],
    authorityLevel: 'Owner',
    scopes: ['FCS', 'Avionics'],
    location: 'Seattle',
    timezone: 'America/Los_Angeles',
    contact: { email: 'jane.smith@example.com', phone: '+1-555-0101' },
    status: 'Active',
    notes: 'Lead systems',
    createdAt: past(120),
    updatedAt: now,
  },
  {
    stakeholderId: 'SH-0002',
    displayName: 'Bob Wilson',
    organization: 'Safety Team',
    stakeholderType: 'Internal',
    discipline: 'Safety',
    roles: ['Safety Engineer', 'SRB Chair'],
    authorityLevel: 'Approver',
    scopes: ['FCS', 'Propulsion'],
    contact: { email: 'bob.wilson@example.com' },
    status: 'Active',
    createdAt: past(100),
    updatedAt: now,
  },
  {
    stakeholderId: 'SH-0003',
    displayName: 'Alice Chen',
    organization: 'Verification',
    stakeholderType: 'Internal',
    discipline: 'Verification',
    roles: ['V&V Lead'],
    authorityLevel: 'Approver',
    scopes: ['Avionics'],
    status: 'Active',
    createdAt: past(90),
    updatedAt: now,
  },
  {
    stakeholderId: 'SH-0004',
    displayName: 'David Park',
    organization: 'CM',
    stakeholderType: 'Internal',
    discipline: 'CM',
    roles: ['Configuration Manager', 'CCB Member'],
    authorityLevel: 'Owner',
    scopes: ['FCS', 'Avionics', 'Propulsion'],
    status: 'Active',
    createdAt: past(80),
    updatedAt: now,
  },
  {
    stakeholderId: 'SH-0005',
    displayName: 'Eva Martinez',
    organization: 'Certification',
    stakeholderType: 'Internal',
    discipline: 'Certification',
    roles: ['Certification Manager'],
    authorityLevel: 'Approver',
    scopes: ['Avionics'],
    status: 'Active',
    createdAt: past(70),
    updatedAt: now,
  },
  {
    stakeholderId: 'SH-0006',
    displayName: 'Frank Liu',
    organization: 'Supplier A',
    stakeholderType: 'Supplier',
    discipline: 'HW',
    roles: ['Hardware Lead'],
    authorityLevel: 'Reviewer',
    scopes: ['Avionics'],
    status: 'Active',
    createdAt: past(60),
    updatedAt: now,
  },
  {
    stakeholderId: 'SH-0007',
    displayName: 'Grace Kim',
    organization: 'Authority Liaison',
    stakeholderType: 'Authority',
    discipline: 'Certification',
    roles: ['Authority Interface'],
    authorityLevel: 'Approver',
    scopes: [],
    status: 'Active',
    createdAt: past(50),
    updatedAt: now,
  },
  {
    stakeholderId: 'SH-0008',
    displayName: 'Henry Brown',
    organization: 'QA',
    stakeholderType: 'Internal',
    discipline: 'QA',
    roles: ['QA Engineer'],
    authorityLevel: 'Reviewer',
    scopes: ['FCS'],
    status: 'Inactive',
    createdAt: past(200),
    updatedAt: past(30),
  },
]

export const MOCK_COMMITTEES: Committee[] = [
  {
    groupId: 'GR-CCB-SYS',
    name: 'System CCB',
    type: 'CCB',
    members: ['SH-0001', 'SH-0004', 'SH-0002'],
    chair: 'SH-0004',
    defaultReviewersFor: ['Baseline', 'Release'],
    meetingCadence: 'Weekly Tue 10:00',
    notes: 'System-level change control.',
  },
  {
    groupId: 'GR-SRB',
    name: 'Safety Review Board',
    type: 'ReviewBoard',
    members: ['SH-0002', 'SH-0001', 'SH-0003'],
    chair: 'SH-0002',
    defaultReviewersFor: ['SafetyGate'],
    meetingCadence: 'Bi-weekly Thu 14:00',
  },
  {
    groupId: 'GR-AUTH-IF',
    name: 'Authority Interface Board',
    type: 'AuthorityInterface',
    members: ['SH-0007', 'SH-0005', 'SH-0002'],
    chair: 'SH-0005',
    defaultReviewersFor: ['CertificationPackage'],
    meetingCadence: 'Monthly',
    notes: 'Formal authority interface.',
  },
  {
    groupId: 'GR-VERIF',
    name: 'Verification Review Panel',
    type: 'ReviewBoard',
    members: ['SH-0003', 'SH-0001', 'SH-0004'],
    chair: 'SH-0003',
    defaultReviewersFor: ['VerificationReview'],
    meetingCadence: 'Weekly Wed 09:00',
  },
]

export const MOCK_RACI: RaciEntry[] = [
  {
    raciId: 'RACI-001',
    subjectType: 'Deliverable',
    subjectRef: 'Certification Package',
    responsible: ['SH-0005'],
    accountable: ['SH-0005'],
    consulted: ['SH-0002', 'SH-0003'],
    informed: ['SH-0001', 'SH-0004', 'SH-0007'],
  },
  {
    raciId: 'RACI-002',
    subjectType: 'Deliverable',
    subjectRef: 'CM Baseline Approval',
    responsible: ['SH-0004'],
    accountable: ['SH-0004'],
    consulted: ['SH-0001'],
    informed: ['SH-0002', 'SH-0003', 'SH-0005'],
  },
  {
    raciId: 'RACI-003',
    subjectType: 'SystemElement',
    subjectRef: 'FCS Subsystem',
    responsible: ['SH-0001'],
    accountable: ['SH-0001'],
    consulted: ['SH-0002', 'SH-0003'],
    informed: ['SH-0004', 'SH-0006'],
  },
  {
    raciId: 'RACI-004',
    subjectType: 'Module',
    subjectRef: 'Safety Gate 2',
    responsible: ['SH-0002'],
    accountable: ['SH-0002'],
    consulted: ['SH-0001', 'SH-0005'],
    informed: ['SH-0007'],
  },
  {
    raciId: 'RACI-005',
    subjectType: 'Deliverable',
    subjectRef: 'PDR Baseline',
    responsible: ['SH-0004', 'SH-0001'],
    accountable: ['SH-0004'],
    consulted: ['SH-0002', 'SH-0003'],
    informed: ['SH-0005', 'SH-0006'],
  },
  {
    raciId: 'RACI-006',
    subjectType: 'SystemElement',
    subjectRef: 'Avionics LRU Integration',
    responsible: ['SH-0003', 'SH-0006'],
    accountable: [], // gap: no accountable
    consulted: ['SH-0001'],
    informed: ['SH-0004'],
    riskFlag: true,
  },
  {
    raciId: 'RACI-007',
    subjectType: 'Deliverable',
    subjectRef: 'Verification Review Report',
    responsible: ['SH-0003'],
    accountable: ['SH-0003'],
    consulted: ['SH-0001', 'SH-0002'],
    informed: ['SH-0005', 'SH-0007'],
  },
  {
    raciId: 'RACI-008',
    subjectType: 'Module',
    subjectRef: 'Deviation Waiver D-001',
    responsible: ['SH-0004'],
    accountable: ['SH-0002'],
    consulted: ['SH-0005'],
    informed: ['SH-0007'],
  },
]

export const MOCK_APPROVAL_RULES: ApprovalRule[] = [
  {
    ruleId: 'RULE-001',
    appliesTo: 'Baseline',
    condition: 'DAL=A OR SafetyCritical=true',
    requiredApprovals: 2,
    requiredGroups: ['GR-CCB-SYS'],
    twoPersonRule: true,
    delegationAllowed: false,
    escalationPath: 'Program Manager',
    status: 'Active',
  },
  {
    ruleId: 'RULE-002',
    appliesTo: 'CertificationPackage',
    condition: 'All certification objectives complete',
    requiredApprovals: 1,
    requiredGroups: ['GR-AUTH-IF'],
    twoPersonRule: false,
    delegationAllowed: true,
    status: 'Active',
  },
  {
    ruleId: 'RULE-003',
    appliesTo: 'SafetyGate',
    condition: 'SafetyCritical=true',
    requiredApprovals: 2,
    requiredGroups: ['GR-SRB'],
    twoPersonRule: true,
    delegationAllowed: false,
    status: 'Active',
  },
  {
    ruleId: 'RULE-004',
    appliesTo: 'Release',
    condition: 'Baseline approved',
    requiredApprovals: 1,
    requiredGroups: ['GR-CCB-SYS'],
    twoPersonRule: false,
    delegationAllowed: true,
    status: 'Disabled',
  },
]

export const MOCK_REQUESTS: Request[] = [
  {
    requestId: 'REQ-ACT-001',
    type: 'Approval',
    priority: 'High',
    status: 'Open',
    targetType: 'Stakeholder',
    targetId: 'SH-0002',
    title: 'Approve Safety Assessment',
    message: 'Please review and approve the updated safety assessment for FCS.',
    linkedObject: { kind: 'Baseline', id: 'BL-2026-03-PDR' },
    dueDate: new Date(Date.now() + 5 * 86400000).toISOString().slice(0, 10),
    createdBy: 'SH-0001',
    createdAt: past(3),
    updatedAt: now,
  },
  {
    requestId: 'REQ-ACT-002',
    type: 'Review',
    priority: 'Medium',
    status: 'InProgress',
    targetType: 'Group',
    targetId: 'GR-CCB-SYS',
    title: 'CCB Review of BL-2026-02',
    message: 'Review baseline BL-2026-02 in next CCB.',
    dueDate: new Date(Date.now() + 2 * 86400000).toISOString().slice(0, 10),
    createdBy: 'SH-0004',
    createdAt: past(5),
    updatedAt: now,
  },
  {
    requestId: 'REQ-ACT-003',
    type: 'ActionItem',
    priority: 'High',
    status: 'Done',
    targetType: 'Stakeholder',
    targetId: 'SH-0003',
    title: 'Complete V&V traceability',
    message: 'Close traceability gaps for Avionics.',
    dueDate: past(2).slice(0, 10),
    createdBy: 'SH-0001',
    createdAt: past(14),
    updatedAt: past(1),
  },
  {
    requestId: 'REQ-ACT-004',
    type: 'Info',
    priority: 'Low',
    status: 'Open',
    targetType: 'Stakeholder',
    targetId: 'SH-0007',
    title: 'Authority meeting prep',
    message: 'Summary for next authority meeting.',
    createdBy: 'SH-0005',
    createdAt: past(1),
    updatedAt: now,
  },
  {
    requestId: 'REQ-ACT-005',
    type: 'Approval',
    priority: 'Medium',
    status: 'Blocked',
    targetType: 'Stakeholder',
    targetId: 'SH-0004',
    title: 'Approve CI snapshot',
    message: 'Approve snapshot for PDR baseline.',
    linkedObject: { kind: 'Baseline', id: 'BL-2026-03-PDR' },
    dueDate: past(5).slice(0, 10), // overdue
    createdBy: 'SH-0001',
    createdAt: past(10),
    updatedAt: now,
  },
]

export const MOCK_COMMUNICATION_LOG: CommunicationLogEntry[] = [
  {
    commId: 'COMM-001',
    type: 'Announcement',
    audience: { type: 'All', ref: '*' },
    timestamp: past(2),
    summary: 'PDR baseline BL-2026-03 submitted for approval.',
    createdBy: 'SH-0004',
  },
  {
    commId: 'COMM-002',
    type: 'ReviewRequest',
    audience: { type: 'Group', ref: 'GR-SRB' },
    timestamp: past(4),
    summary: 'Safety Gate 2 review scheduled for next Thursday.',
    createdBy: 'SH-0002',
  },
  {
    commId: 'COMM-003',
    type: 'Decision',
    audience: { type: 'Group', ref: 'GR-CCB-SYS' },
    timestamp: past(7),
    summary: 'CCB approved baseline BL-2026-02.',
    linkedObject: { kind: 'Baseline', id: 'BL-2026-02' },
    createdBy: 'SH-0004',
  },
  {
    commId: 'COMM-004',
    type: 'Note',
    audience: { type: 'StakeholderType', ref: 'Internal' },
    timestamp: past(10),
    summary: 'Reminder: certification package draft due EOW.',
    createdBy: 'SH-0005',
  },
]

export const MOCK_AUDIT_EVENTS: AuditEvent[] = [
  {
    eventId: 'EVT-001',
    timestamp: past(120),
    actor: 'system',
    action: 'CREATE_STAKEHOLDER',
    objectRef: { kind: 'Stakeholder', id: 'SH-0001' },
    details: 'Stakeholder created',
  },
  {
    eventId: 'EVT-002',
    timestamp: past(100),
    actor: 'system',
    action: 'CREATE_GROUP',
    objectRef: { kind: 'Group', id: 'GR-CCB-SYS' },
    details: 'Committee created',
  },
  {
    eventId: 'EVT-003',
    timestamp: past(30),
    actor: 'SH-0004',
    action: 'UPDATE_REQUEST',
    objectRef: { kind: 'Request', id: 'REQ-ACT-002' },
    details: 'Status changed to InProgress',
  },
]
