/**
 * CI/CD Pipeline Generator
 * Produces platform-specific CI/CD configuration files that:
 *   1. Optionally run MATLAB scripts to build binary .sldd / .mat artifacts
 *      (commented out by default — requires a licensed MATLAB runner)
 *   2. Create a versioned release/tag on every push to the default branch
 *
 * Each platform receives its own canonical CI filename:
 *   GitLab        → .gitlab-ci.yml
 *   GitHub        → .github/workflows/release.yml
 *   Bitbucket     → bitbucket-pipelines.yml
 *   Azure DevOps  → azure-pipelines.yml
 */

export type CIPlatform = 'gitlab' | 'github' | 'bitbucket' | 'azuredevops'

export interface CIPipelineFile {
  /** Path relative to repo root, e.g. ".github/workflows/release.yml" */
  filename: string
  content: string
}

// Formats that require running MATLAB to produce binary output
const MATLAB_FORMATS = ['matlab', 'simulink', 'mat'] as const
type MatlabFormat = typeof MATLAB_FORMATS[number]

interface MatlabStep {
  script: string    // MATLAB -batch command
  produces: string  // output filename
}

function matlabSteps(formats: string[]): MatlabStep[] {
  const steps: MatlabStep[] = []
  if (formats.includes('simulink')) {
    steps.push({ script: "run('create_parameters_sldd.m')", produces: 'parameters.sldd' })
  }
  if (formats.includes('mat')) {
    steps.push({ script: "run('create_parameters_mat.m')", produces: 'parameters.mat' })
  }
  if (formats.includes('matlab') && !formats.includes('mat')) {
    // parameters.m calls save() internally, so running it also produces parameters.mat
    steps.push({ script: "run('parameters.m')", produces: 'parameters.mat' })
  }
  return steps
}

function hasMatlabFormats(formats: string[]): boolean {
  return (MATLAB_FORMATS as readonly string[]).some(f => formats.includes(f))
}

// ---------------------------------------------------------------------------
// GitLab CI  (.gitlab-ci.yml)
// ---------------------------------------------------------------------------
function buildGitLabCI(formats: string[], branch: string): CIPipelineFile {
  const steps = matlabSteps(formats)
  const artifactPaths = steps.map(s => `      - ${s.produces}`).join('\n')
  const matlabCommands = steps.map(s =>
    `    - matlab -batch "${s.script}"   # produces ${s.produces}`
  ).join('\n')

  const matlabBlock = hasMatlabFormats(formats) ? `
# ---------------------------------------------------------------------------
# MATLAB Build (optional)
# Requires: a runner with MATLAB installed OR the MathWorks Docker image
#   image: mathworks/matlab:R2024b
# and a valid network or file-based license.
# Reference: https://hub.docker.com/r/mathworks/matlab
#
# To enable: rename '.matlab-build' to 'matlab-build' (remove the leading dot).
# ---------------------------------------------------------------------------
.matlab-build:
  stage: build
  image: mathworks/matlab:R2024b   # change to your MATLAB version
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    MLM_LICENSE_FILE: ""           # set to your license server: port@host
  script:
${matlabCommands}
  artifacts:
    name: "matlab-artifacts-\${CI_COMMIT_SHORT_SHA}"
    paths:
${artifactPaths}
    expire_in: never

` : ''

  const content = `# Engineering Parameters — GitLab CI/CD Pipeline
# Generated by Engineering Tool.
#
# This pipeline:
#   1. Optionally runs MATLAB to produce binary artifacts (.sldd, .mat)
#      — disabled by default, see MATLAB Build section below
#   2. Creates a versioned GitLab Release and git tag on every push to ${branch}
#
# Requirements for the release job:
#   - GitLab Runner with Docker or Shell executor
#   - The pipeline token has read_repository + write_repository access (default)

stages:
  - build
  - release
${matlabBlock}
# ---------------------------------------------------------------------------
# Release — creates a versioned git tag and GitLab Release
# ---------------------------------------------------------------------------
create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    TAG: "v\${CI_PIPELINE_IID}"
  script:
    - echo "Creating release \${TAG} for commit \${CI_COMMIT_SHORT_SHA}"
  release:
    tag_name: "\${TAG}"
    name: "Parameter Set \${TAG}"
    description: |
      Auto-generated parameter snapshot.

      Branch: \${CI_COMMIT_BRANCH}
      Commit: \${CI_COMMIT_SHA}
      Pipeline: \${CI_PIPELINE_URL}
`

  return { filename: '.gitlab-ci.yml', content }
}

// ---------------------------------------------------------------------------
// GitHub Actions  (.github/workflows/release.yml)
// ---------------------------------------------------------------------------
function buildGitHubActions(formats: string[], branch: string): CIPipelineFile {
  const steps = matlabSteps(formats)

  const matlabBlock = hasMatlabFormats(formats) ? `
      # -----------------------------------------------------------------------
      # MATLAB Build (optional — requires a MATLAB license)
      # Uncomment the steps below and set your MATLAB release version.
      # Reference: https://github.com/matlab-actions/setup-matlab
      # -----------------------------------------------------------------------
      # - name: Set up MATLAB
      #   uses: matlab-actions/setup-matlab@v2
      #   with:
      #     release: R2024b   # change to your MATLAB version
      #
${steps.map(s =>
  `      # - name: Run MATLAB — ${s.produces}\n` +
  `      #   uses: matlab-actions/run-command@v2\n` +
  `      #   with:\n` +
  `      #     command: "${s.script}"   # produces ${s.produces}\n      #`
).join('\n')}
      # -----------------------------------------------------------------------
` : ''

  const allFilesGlob = [
    'parameters.* create_parameters_*.m README.md',
    ...steps.map(s => `# ${s.produces}  ← uncomment after enabling MATLAB build above`),
  ]

  const content = `# Engineering Parameters — Build & Release
# Generated by Engineering Tool.
#
# This workflow:
#   1. Optionally runs MATLAB to produce binary artifacts (.sldd, .mat)
#      — disabled by default, see MATLAB Build section below
#   2. Creates a versioned GitHub Release with parameter files attached
#
# Reference for MATLAB in GitHub Actions:
#   https://github.com/matlab-actions/setup-matlab

name: Build & Release Parameters

on:
  push:
    branches: ["${branch}"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
${matlabBlock}
      - name: Create versioned release
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          TAG="v\$(date -u +%Y.%m.%d).\${GITHUB_RUN_NUMBER}"
          # Collect all parameter files present in the workspace
          FILES=\$(ls parameters.* create_parameters_*.m README.md 2>/dev/null | tr '\\n' ' ')
          # After enabling the MATLAB build above, also add binary artifacts:
${steps.map(s => `          # FILES="\$FILES ${s.produces}"`).join('\n')}
          gh release create "\$TAG" \\
            --title "Parameters \$TAG" \\
            --notes "Automated parameter snapshot. Commit: \${GITHUB_SHA::7}" \\
            \$FILES
`

  return { filename: '.github/workflows/release.yml', content }
}

// ---------------------------------------------------------------------------
// Bitbucket Pipelines  (bitbucket-pipelines.yml)
// ---------------------------------------------------------------------------
function buildBitbucketPipelines(formats: string[], branch: string): CIPipelineFile {
  const steps = matlabSteps(formats)

  const matlabStepBlock = hasMatlabFormats(formats) ? `
      # -----------------------------------------------------------------------
      # MATLAB Build (optional — requires a MATLAB-licensed runner)
      # Reference: https://hub.docker.com/r/mathworks/matlab
      # To enable: uncomment the step block below.
      # -----------------------------------------------------------------------
      # - step:
      #     name: "Build MATLAB artifacts"
      #     image: mathworks/matlab:R2024b   # change to your MATLAB version
      #     script:
${steps.map(s =>
  `      #       - matlab -batch "${s.script}"   # produces ${s.produces}`
).join('\n')}
      #     artifacts:
${steps.map(s => `      #       - ${s.produces}`).join('\n')}
      # -----------------------------------------------------------------------
` : ''

  const content = `# Engineering Parameters — Bitbucket Pipelines
# Generated by Engineering Tool.
#
# This pipeline:
#   1. Optionally runs MATLAB to produce binary artifacts (.sldd, .mat)
#      — disabled by default, see MATLAB Build section below
#   2. Tags the commit as a versioned release
#
# Reference for MATLAB in Bitbucket Pipelines:
#   https://hub.docker.com/r/mathworks/matlab

image: atlassian/default-image:4

pipelines:
  branches:
    ${branch}:
${matlabStepBlock}
      - step:
          name: "Tag release"
          script:
            - TAG="v\$(date -u +%Y.%m.%d).\${BITBUCKET_BUILD_NUMBER}"
            - git config user.email "ci@parameters.local"
            - git config user.name "Parameter CI"
            - git tag "\$TAG"
            - git push origin "\$TAG"
`

  return { filename: 'bitbucket-pipelines.yml', content }
}

// ---------------------------------------------------------------------------
// Azure DevOps  (azure-pipelines.yml)
// ---------------------------------------------------------------------------
function buildAzurePipelines(formats: string[], branch: string): CIPipelineFile {
  const steps = matlabSteps(formats)

  const matlabBlock = hasMatlabFormats(formats) ? `
  # -------------------------------------------------------------------------
  # MATLAB Build (optional)
  # Requires the MathWorks Azure DevOps extension and a licensed MATLAB agent.
  # Install extension:
  #   https://marketplace.visualstudio.com/items?itemName=MathWorks.matlab-azure-devops-extension
  # Then uncomment the tasks below and set your MATLAB release version.
  # -------------------------------------------------------------------------
  # - task: InstallMATLAB@1
  #   inputs:
  #     release: \$(MATLAB_RELEASE)
  #
${steps.map(s =>
  `  # - task: RunMATLABCommand@1\n` +
  `  #   inputs:\n` +
  `  #     command: "${s.script}"   # produces ${s.produces}\n  #`
).join('\n')}
  # -------------------------------------------------------------------------

` : ''

  const artifactIncludes = [
    '      parameters.*',
    '      create_parameters_*.m',
    '      README.md',
    ...steps.map(s => `      # ${s.produces}  ← uncomment after enabling MATLAB build above`),
  ].join('\n')

  const content = `# Engineering Parameters — Azure Pipelines
# Generated by Engineering Tool.
#
# This pipeline:
#   1. Optionally runs MATLAB to produce binary artifacts (.sldd, .mat)
#      — disabled by default, see MATLAB Build section below
#   2. Tags the commit and publishes parameter files as build artifacts
#
# Note: the tagging step requires "Allow scripts to access the OAuth token"
# to be enabled in Pipeline Settings > General.

trigger:
  branches:
    include:
      - ${branch}

pool:
  vmImage: ubuntu-latest

variables:
  MATLAB_RELEASE: 'R2024b'   # change to your MATLAB version
${matlabBlock}
steps:
  - checkout: self
    persistCredentials: true

  - script: |
      TAG="v\$(date -u +%Y.%m.%d).\$(Build.BuildId)"
      git config user.email "ci@parameters.local"
      git config user.name "Parameter CI"
      git tag "\$TAG"
      git push origin "\$TAG"
    displayName: "Tag release"
    env:
      SYSTEM_ACCESSTOKEN: \$(System.AccessToken)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '.'
      artifactName: "parameters-\$(Build.BuildId)"
      publishLocation: Container
    displayName: "Publish parameter files"
`

  return { filename: 'azure-pipelines.yml', content }
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------
export function buildCIPipeline(
  platform: CIPlatform,
  formats: string[],
  branch: string
): CIPipelineFile {
  switch (platform) {
    case 'gitlab':      return buildGitLabCI(formats, branch)
    case 'github':      return buildGitHubActions(formats, branch)
    case 'bitbucket':   return buildBitbucketPipelines(formats, branch)
    case 'azuredevops': return buildAzurePipelines(formats, branch)
  }
}
