import type { Risk } from './types'

const baseRisks: Omit<Risk, 'id'>[] = [
  {
    title: 'Schedule slip on flight control software delivery',
    type: 'Program',
    affectedArea: 'Subsystem',
    owner: 'Program Manager',
    likelihood: 4,
    impact: 4,
    status: 'Mitigating',
    targetDate: '2025-03-15',
    description: 'Risk of delay in FCS software milestones due to dependency on external test rig availability.',
    mitigationDescription: 'Early booking of test rig; parallel simulation campaign.',
    mitigationActions: ['Secure test rig slots Q1', 'Run SIL tests in parallel'],
    mitigationTargetDate: '2025-02-28',
    residualRiskRating: 'Low',
    accepted: false,
    linkedCounts: { Requirements: 2, 'Verification Activities': 1 },
  },
  {
    title: 'EMI from power converter affecting navigation sensors',
    type: 'Technical',
    affectedArea: 'Subsystem',
    owner: 'Avionics Lead',
    likelihood: 3,
    impact: 5,
    status: 'Open',
    targetDate: '2025-04-01',
    description: 'Potential electromagnetic interference from new power converter design.',
    accepted: false,
    linkedCounts: { Interfaces: 1, Issues: 0 },
  },
  {
    title: 'Single point of failure in hydraulic supply',
    type: 'Safety',
    affectedArea: 'Subsystem',
    owner: 'Safety Engineer',
    likelihood: 2,
    impact: 5,
    status: 'Watch',
    targetDate: '2025-05-01',
    description: 'Hydraulic pump has no redundancy; loss could affect landing gear and brakes.',
    mitigationDescription: 'Design review for backup or procedural mitigation.',
    mitigationActions: ['Preliminary backup pump study'],
    mitigationTargetDate: '2025-06-30',
    residualRiskRating: 'Medium',
    accepted: false,
    linkedCounts: { Requirements: 1, 'Change Requests': 1 },
  },
  {
    title: 'Non-compliance with updated DO-178C guidance',
    type: 'Compliance',
    affectedArea: 'Requirement',
    owner: 'Certification Lead',
    likelihood: 2,
    impact: 4,
    status: 'Closed',
    targetDate: '2025-01-20',
    description: 'Software process alignment with latest DO-178C interpretation.',
    mitigationDescription: 'Process update and audit completed.',
    accepted: false,
    linkedCounts: { Requirements: 3, 'Verification Activities': 1 },
  },
  {
    title: 'Supplier delay on actuator delivery',
    type: 'Supplier',
    affectedArea: 'Program',
    owner: 'Supply Chain',
    likelihood: 4,
    impact: 3,
    status: 'Accepted',
    targetDate: '2025-02-10',
    description: 'Actuator supplier has indicated possible 2-week slip.',
    acceptanceRationale: 'Buffer in program schedule; no impact to critical path.',
    acceptedBy: 'Program Manager',
    accepted: true,
    linkedCounts: {},
  },
  {
    title: 'Interface change between FCS and actuators',
    type: 'Technical',
    affectedArea: 'Interface',
    owner: 'Systems Engineer',
    likelihood: 3,
    impact: 3,
    status: 'Open',
    targetDate: '2025-03-30',
    description: 'Protocol change may require re-qualification of both sides.',
    accepted: false,
    linkedCounts: { Interfaces: 1, Requirements: 1 },
  },
  {
    title: 'Requirement ambiguity on fault detection time',
    type: 'Technical',
    affectedArea: 'Requirement',
    owner: 'Requirements Lead',
    likelihood: 4,
    impact: 2,
    status: 'Mitigating',
    targetDate: '2025-02-28',
    description: 'REQ-412 does not specify max detection time for sensor fault.',
    mitigationDescription: 'Clarify with stakeholder and update requirement.',
    mitigationActions: ['Stakeholder meeting', 'Update REQ-412'],
    mitigationTargetDate: '2025-02-15',
    residualRiskRating: 'Low',
    accepted: false,
    linkedCounts: { Requirements: 1 },
  },
]

export const MOCK_RISKS: Risk[] = baseRisks.map((r, i) => ({
  ...r,
  id: `RISK-${String(i + 1).padStart(3, '0')}`,
  linkedCounts: r.linkedCounts ?? {},
}))
