// N-2.2 (#425) — the PSAC section-content builder.
//
// Maps a ComposedAuditPackage + the PSAC section map to a renderer-agnostic
// intermediate representation (an ordered list of `PsacRenderSection`). Both
// the DOCX and PDF renderers consume THIS — so the two formats are guaranteed
// to carry the same content and the 14-section structure in the same order.
//
// The "never omit a numbered section" rule lives here: every section in the
// map produces exactly one PsacRenderSection. A section with no composed data
// emits an `empty` block carrying the engineer-voice reason.
import type { ComposedAuditPackage } from '../types'
import type { PackageManifest } from '../types'
import { PSAC_SECTION_MAP, psacHeading } from '../sectionMaps/psac.sectionMap'
import type { PsacSection } from '../sectionMaps/psac.sectionMap'

/** A block inside a rendered section — the renderer switches on `type`. */
export type PsacBlock =
  | { type: 'paragraph'; text: string }
  | { type: 'keyValue'; pairs: { label: string; value: string }[] }
  | { type: 'table'; headers: string[]; rows: string[][] }
  | { type: 'empty'; reason: string }

/** One fully-resolved section, ready to render. */
export interface PsacRenderSection {
  number: string
  title: string
  heading: string
  description: string
  blocks: PsacBlock[]
}

function fmtDate(iso: string): string {
  return iso.slice(0, 10)
}

/** Build the ordered render sections for a PSAC. `manifest` feeds Appendix B. */
export function buildPsacRenderSections(
  composed: ComposedAuditPackage,
  manifest: PackageManifest,
): PsacRenderSection[] {
  return PSAC_SECTION_MAP.map((section) => ({
    number: section.number,
    title: section.title,
    heading: psacHeading(section),
    description: section.description,
    blocks: blocksFor(section, composed, manifest),
  }))
}

function blocksFor(
  section: PsacSection,
  c: ComposedAuditPackage,
  manifest: PackageManifest,
): PsacBlock[] {
  switch (section.kind) {
    case 'titlePage':
      return [
        {
          type: 'keyValue',
          pairs: [
            { label: 'Document', value: 'Plan for Software Aspects of Certification (PSAC)' },
            { label: 'Project', value: c.project.name },
            { label: 'Certification authority', value: c.certContext.authority },
            { label: 'Certification basis', value: c.certContext.certBasis },
            { label: 'PSAC revision', value: '1.0 (generated)' },
            { label: 'Generated at', value: c.composedAt },
            { label: 'Generated by', value: manifest.generatedBy },
            { label: 'Document status', value: 'Draft — composed from current project state' },
          ],
        },
        {
          type: 'paragraph',
          text:
            'This PSAC is composed from the current state of the project. It is a planning document: it states what the applicant intends to do and how compliance will be shown.',
        },
      ]

    case 'introduction':
      return [
        {
          type: 'paragraph',
          text: `This document is the Plan for Software Aspects of Certification for ${c.project.name}. It defines the certification scope, the certification authority (${c.certContext.authority}), and the means by which compliance with the certification basis will be demonstrated.`,
        },
        c.project.description
          ? { type: 'paragraph', text: c.project.description }
          : {
              type: 'empty',
              reason:
                'No project description recorded. Add a project description in the project settings.',
            },
      ]

    case 'systemOverview':
      return [
        {
          type: 'paragraph',
          text: `The system covered by this plan is developed under the ${c.certContext.certBasis} certification basis. The standards applied are: ${c.certContext.standards.join(', ')}.`,
        },
        {
          type: 'empty',
          reason:
            'No detailed system architecture composed for this section. Capture the system context in the Certification Plan tab.',
        },
      ]

    case 'softwareOverview':
      return [
        {
          type: 'paragraph',
          text: `This plan covers ${c.counts.requirements} software requirement(s) traced to ${c.counts.objectives} certification objective(s).`,
        },
        c.counts.requirements === 0
          ? {
              type: 'empty',
              reason:
                'No requirements linked to certification objectives yet. Link requirements to objectives in the Objectives & MoC tab.',
            }
          : {
              type: 'paragraph',
              text:
                'The major software components are defined by the requirement population and its trace to the certification objectives in section 4.',
            },
      ]

    case 'certificationConsiderations':
      return [
        {
          type: 'keyValue',
          pairs: [
            { label: 'Certification authority', value: c.certContext.authority },
            { label: 'Certification basis', value: c.certContext.certBasis },
            { label: 'Applied standards', value: c.certContext.standards.join(', ') },
            { label: 'Objectives in scope', value: String(c.counts.objectives) },
          ],
        },
        {
          type: 'paragraph',
          text:
            'The certification basis, the regulatory means of compliance, and the software level are stated in the following sub-sections.',
        },
      ]

    case 'certificationBasis': {
      const rows = c.objectives.map((o) => [o.objId, o.regRef, o.moc, o.status])
      return rows.length
        ? [
            {
              type: 'paragraph',
              text: `The certification basis is ${c.certContext.certBasis}. The means of compliance per objective:`,
            },
            {
              type: 'table',
              headers: ['Objective', 'Reg ref', 'Means of compliance', 'Status'],
              rows,
            },
          ]
        : [
            {
              type: 'empty',
              reason:
                'No certification objectives defined. Add objectives in the Objectives & MoC tab to populate the certification basis.',
            },
          ]
    }

    case 'softwareLevel': {
      const byCrit = new Map<string, number>()
      for (const o of c.objectives) byCrit.set(o.criticality, (byCrit.get(o.criticality) ?? 0) + 1)
      const rows = [...byCrit.entries()].map(([crit, n]) => [crit, String(n)])
      return rows.length
        ? [
            {
              type: 'paragraph',
              text:
                'The Development Assurance Level is driven by the failure-condition criticality of the objectives in scope. Objective criticality distribution:',
            },
            { type: 'table', headers: ['Criticality', 'Objective count'], rows },
          ]
        : [
            {
              type: 'empty',
              reason:
                'No objectives defined, so no software level can be derived. Add objectives with a criticality in the Objectives & MoC tab.',
            },
          ]
    }

    case 'softwareLifeCycle':
      return [
        {
          type: 'paragraph',
          text: `The applicant follows the life-cycle processes defined by ${c.certContext.standards.join(', ')} — planning, development, verification, configuration management, and quality assurance — each with documented transition criteria.`,
        },
      ]

    case 'softwareLifeCycleData': {
      // The objective-satisfaction table — the compliance-matrix core.
      if (c.objectives.length === 0) {
        return [
          {
            type: 'empty',
            reason:
              'No certification objectives defined. The objective-satisfaction table is empty until objectives are added in the Objectives & MoC tab.',
          },
        ]
      }
      const blocks: PsacBlock[] = [
        {
          type: 'paragraph',
          text:
            'Each applicable objective below lists its means of compliance, the requirements satisfying it, the electronic-signature chain per requirement, and the linked evidence.',
        },
      ]
      const rows: string[][] = []
      for (const obj of c.objectives) {
        if (obj.requirements.length === 0) {
          rows.push([
            `${obj.objId} (${obj.regRef})`,
            obj.moc,
            '— no requirements linked —',
            '—',
            '—',
          ])
          continue
        }
        for (const req of obj.requirements) {
          const chain =
            req.signatureChain.length === 0
              ? '(unsigned)'
              : req.signatureChain
                  .map(
                    (s) =>
                      `${s.signerName ?? s.signerUserId} [${s.meaningCode}] ${fmtDate(s.signedAt)}${s.superseded ? ' (superseded)' : ''}`,
                  )
                  .join('; ')
          const results =
            req.testResultStatuses.length === 0 ? '—' : req.testResultStatuses.join(', ')
          rows.push([
            `${obj.objId} (${obj.regRef})`,
            obj.moc,
            `${req.requirementKey}: ${req.title}`,
            `${chain} | results: ${results}`,
            req.status,
          ])
        }
      }
      blocks.push({
        type: 'table',
        headers: ['Objective', 'MoC', 'Requirement / signature chain', 'Detail', 'Status'],
        rows,
      })
      return blocks
    }

    case 'evidenceIndex': {
      const seen = new Set<string>()
      const rows: string[][] = []
      for (const obj of c.objectives) {
        for (const ev of obj.evidence) {
          if (seen.has(ev.id)) continue
          seen.add(ev.id)
          rows.push([ev.id.slice(0, 8), ev.evidenceType, ev.title, obj.objId, fmtDate(ev.createdAt)])
        }
      }
      return rows.length
        ? [
            {
              type: 'paragraph',
              text: 'The life-cycle data items referenced by section 4:',
            },
            {
              type: 'table',
              headers: ['Evidence', 'Type', 'Title', 'Supports objective', 'Created'],
              rows,
            },
          ]
        : [
            {
              type: 'empty',
              reason:
                'No evidence linked to the requirements in scope. Link evidence to requirements in the Verification module.',
            },
          ]
    }

    case 'schedule':
      return c.milestones.length
        ? [
            {
              type: 'paragraph',
              text: 'The certification milestones and review points:',
            },
            {
              type: 'table',
              headers: ['Milestone', 'Type', 'Date', 'Status'],
              rows: c.milestones.map((m) => [m.name, m.type, fmtDate(m.date), m.status]),
            },
          ]
        : [
            {
              type: 'empty',
              reason:
                'No certification milestones defined. Add milestones in the Certification Plan tab.',
            },
          ]

    case 'additionalConsiderations':
      return [
        {
          type: 'empty',
          reason:
            'No additional considerations recorded — previously-developed software, COTS, tool qualification, or deviations. Capture these in the Certification Plan tab when they apply.',
        },
      ]

    case 'objectiveSatisfactionSummary':
      return c.objectives.length
        ? [
            {
              type: 'keyValue',
              pairs: [
                { label: 'Objectives total', value: String(c.counts.objectives) },
                { label: 'Complete', value: String(c.counts.objectivesComplete) },
                { label: 'Partial', value: String(c.counts.objectivesPartial) },
                { label: 'Open', value: String(c.counts.objectivesOpen) },
                { label: 'Requirements traced', value: String(c.counts.requirements) },
                { label: 'Evidence items', value: String(c.counts.evidence) },
                { label: 'Signatures recorded', value: String(c.counts.signatures) },
              ],
            },
            {
              type: 'table',
              headers: ['Objective', 'Reg ref', 'Status', 'Requirements', 'Evidence'],
              rows: c.objectives.map((o) => [
                o.objId,
                o.regRef,
                o.status,
                String(o.requirements.length),
                String(o.evidence.length),
              ]),
            },
          ]
        : [
            {
              type: 'empty',
              reason:
                'No objectives defined. The objective satisfaction summary is empty until objectives are added.',
            },
          ]

    case 'packageManifest': {
      // The rendered document carries the graph counts. Per-file sha256 hashes
      // cannot be embedded here (a document cannot hash itself) — they live in
      // manifest.json, which is the canonical, hashable record.
      const blocks: PsacBlock[] = [
        {
          type: 'keyValue',
          pairs: [
            { label: 'Artefact type', value: manifest.artefactType },
            { label: 'Generated at', value: manifest.generatedAt },
            { label: 'Generated by', value: manifest.generatedBy },
            { label: 'Objectives walked', value: String(manifest.graphCounts.objectives) },
            { label: 'Requirements walked', value: String(manifest.graphCounts.requirements) },
            { label: 'Evidence walked', value: String(manifest.graphCounts.evidence) },
            { label: 'Signatures walked', value: String(manifest.graphCounts.signatures) },
          ],
        },
      ]
      if (manifest.files.length) {
        blocks.push({
          type: 'table',
          headers: ['File', 'sha256', 'Bytes'],
          rows: manifest.files.map((f) => [f.name, f.sha256, String(f.bytes)]),
        })
      } else {
        blocks.push({
          type: 'paragraph',
          text:
            'The per-file sha256 hashes and byte counts for every file in this bundle are recorded in manifest.json.',
        })
      }
      return blocks
    }

    default:
      return [{ type: 'empty', reason: 'No data composed for this section.' }]
  }
}
