import type {
  ConfigurationItem,
  Baseline,
  ChangeRequest,
  ReleasePackage,
  DeviationWaiver,
  AuditEvent,
} from './types'

const now = new Date()
const iso = (d: Date) => d.toISOString()

export const MOCK_CONFIGURATION_ITEMS: ConfigurationItem[] = [
  {
    ciId: 'CI-REQ-014',
    name: 'Flight control requirements',
    type: 'Requirement',
    owner: 'J. Smith',
    status: 'Released',
    version: '2.1.0',
    revision: 'Rev C',
    safetyCritical: true,
    dal: 'B',
    lastModified: iso(new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000)),
    tags: ['flight-control', 'pdr'],
    linkedArtifacts: { requirementsCount: 3, testsCount: 5, safetyCount: 2, docsCount: 1 },
    lockState: 'Unlocked',
  },
  {
    ciId: 'CI-SW-002',
    name: 'Autopilot control module',
    type: 'Software',
    owner: 'A. Lee',
    status: 'InReview',
    version: '1.4.0',
    revision: 'Rev B',
    safetyCritical: true,
    dal: 'A',
    lastModified: iso(new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000)),
    tags: ['autopilot', 'software'],
    linkedArtifacts: { requirementsCount: 8, testsCount: 12, safetyCount: 4, docsCount: 2 },
    lockState: 'Unlocked',
  },
  {
    ciId: 'CI-DOC-101',
    name: 'System design document',
    type: 'Document',
    owner: 'M. Chen',
    status: 'Released',
    version: '1.0.0',
    revision: 'Rev A',
    safetyCritical: false,
    lastModified: iso(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000)),
    tags: ['design', 'cdr'],
    linkedArtifacts: { requirementsCount: 0, testsCount: 0, safetyCount: 0, docsCount: 0 },
    lockState: 'FrozenByBaseline',
  },
  {
    ciId: 'CI-INT-003',
    name: 'FCC to actuator interface',
    type: 'Interface',
    owner: 'K. Park',
    status: 'Draft',
    version: '0.2.0',
    revision: 'Rev 0',
    safetyCritical: true,
    dal: 'C',
    lastModified: iso(now),
    tags: ['interface', 'fcc'],
    linkedArtifacts: { requirementsCount: 2, testsCount: 0, safetyCount: 1, docsCount: 0 },
    lockState: 'Unlocked',
  },
  {
    ciId: 'CI-PAR-007',
    name: 'Max flap deflection parameter',
    type: 'Parameter',
    owner: 'J. Smith',
    status: 'Released',
    version: '1.0.0',
    revision: 'Rev A',
    safetyCritical: false,
    lastModified: iso(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000)),
    tags: ['parameters'],
    linkedArtifacts: { requirementsCount: 1, testsCount: 2, safetyCount: 0, docsCount: 0 },
    lockState: 'Unlocked',
  },
  {
    ciId: 'CI-TC-022',
    name: 'Autopilot integration test case',
    type: 'TestCase',
    owner: 'T. Wilson',
    status: 'Released',
    version: '1.1.0',
    revision: 'Rev B',
    safetyCritical: true,
    dal: 'B',
    lastModified: iso(new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000)),
    tags: ['verification', 'integration'],
    linkedArtifacts: { requirementsCount: 2, testsCount: 1, safetyCount: 1, docsCount: 0 },
    lockState: 'Unlocked',
  },
]

export const MOCK_BASELINES: Baseline[] = [
  {
    baselineId: 'BL-2026-03-PDR',
    name: 'PDR Functional Baseline',
    type: 'Functional',
    phase: 'PDR',
    status: 'Frozen',
    createdBy: 'J. Smith',
    createdAt: iso(new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000)),
    approvedBy: 'L. Davis',
    approvedAt: iso(new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000)),
    ciSnapshot: [
      { ciId: 'CI-REQ-014', version: '2.0.0', revision: 'Rev B' },
      { ciId: 'CI-DOC-101', version: '1.0.0', revision: 'Rev A' },
      { ciId: 'CI-PAR-007', version: '1.0.0', revision: 'Rev A' },
    ],
    notes: 'PDR baseline for flight control and design docs.',
    complianceFlags: { do178c: true, arp4754a: true, en9100: true },
  },
  {
    baselineId: 'BL-2026-05-CDR',
    name: 'CDR Allocated Baseline',
    type: 'Allocated',
    phase: 'CDR',
    status: 'Submitted',
    createdBy: 'A. Lee',
    createdAt: iso(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000)),
    ciSnapshot: [
      { ciId: 'CI-REQ-014', version: '2.1.0', revision: 'Rev C' },
      { ciId: 'CI-SW-002', version: '1.4.0', revision: 'Rev B' },
      { ciId: 'CI-DOC-101', version: '1.0.0', revision: 'Rev A' },
      { ciId: 'CI-PAR-007', version: '1.0.0', revision: 'Rev A' },
      { ciId: 'CI-TC-022', version: '1.1.0', revision: 'Rev B' },
    ],
    notes: 'CDR allocated baseline including software and test cases.',
    complianceFlags: { do178c: true, arp4754a: true, en9100: true },
  },
  {
    baselineId: 'BL-2026-01-SRR',
    name: 'SRR Product Baseline',
    type: 'Product',
    phase: 'SRR',
    status: 'Superseded',
    createdBy: 'M. Chen',
    createdAt: iso(new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000)),
    approvedBy: 'L. Davis',
    approvedAt: iso(new Date(now.getTime() - 88 * 24 * 60 * 60 * 1000)),
    ciSnapshot: [
      { ciId: 'CI-REQ-014', version: '1.0.0', revision: 'Rev A' },
      { ciId: 'CI-DOC-101', version: '0.9.0', revision: 'Rev 0' },
    ],
    notes: 'Superseded by PDR baseline.',
    complianceFlags: { do178c: false, arp4754a: true, en9100: false },
  },
]

export const MOCK_CHANGE_REQUESTS: ChangeRequest[] = [
  {
    crId: 'CR-045',
    title: 'Extend flap deflection limits for crosswind',
    priority: 'Normal',
    status: 'UnderReview',
    impactedCIs: ['CI-REQ-014', 'CI-PAR-007'],
    safetyImpact: true,
    ccbLevel: 'SystemCCB',
    submittedBy: 'K. Park',
    submittedAt: iso(new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000)),
    justification: 'Customer request for extended crosswind envelope.',
  },
  {
    crId: 'CR-044',
    title: 'Update autopilot gain parameters',
    priority: 'Urgent',
    status: 'Approved',
    impactedCIs: ['CI-SW-002'],
    safetyImpact: true,
    ccbLevel: 'SoftwareCCB',
    submittedBy: 'A. Lee',
    submittedAt: iso(new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000)),
    decisionBy: 'L. Davis',
    decisionAt: iso(new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000)),
    justification: 'Stability margin improvement from V&V.',
  },
  {
    crId: 'CR-043',
    title: 'Documentation typo corrections',
    priority: 'Normal',
    status: 'Implemented',
    impactedCIs: ['CI-DOC-101'],
    safetyImpact: false,
    ccbLevel: 'SystemCCB',
    submittedBy: 'M. Chen',
    submittedAt: iso(new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000)),
    decisionBy: 'J. Smith',
    decisionAt: iso(new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000)),
    justification: 'Editorial only.',
  },
]

export const MOCK_RELEASES: ReleasePackage[] = [
  {
    releaseId: 'REL-2026.04',
    name: 'April 2026 internal build',
    target: 'Internal',
    status: 'Approved',
    baselineRef: 'BL-2026-03-PDR',
    includedItems: [
      { ciId: 'CI-REQ-014', version: '2.0.0', revision: 'Rev B' },
      { ciId: 'CI-DOC-101', version: '1.0.0', revision: 'Rev A' },
      { ciId: 'CI-PAR-007', version: '1.0.0', revision: 'Rev A' },
    ],
    releaseNotes: 'PDR baseline release for internal testing.\n\n- Flight control requirements v2.0\n- System design document v1.0\n- Parameter set v1.0',
    approvals: [
      { role: 'Config Manager', name: 'L. Davis', signedAt: iso(new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000)) },
      { role: 'CCB Chair', name: 'J. Smith', signedAt: iso(new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000)) },
    ],
  },
  {
    releaseId: 'REL-2026.03',
    name: 'March 2026 customer delivery',
    target: 'Customer',
    status: 'Draft',
    baselineRef: 'BL-2026-05-CDR',
    includedItems: [],
    releaseNotes: '',
    approvals: [],
  },
]

export const MOCK_DEVIATIONS_WAIVERS: DeviationWaiver[] = [
  {
    dwId: 'DW-012',
    type: 'Waiver',
    title: 'Temporary waiver for test harness delay',
    linkedCIs: ['CI-TC-022'],
    riskLevel: 'Low',
    validUntil: iso(new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000)),
    status: 'Approved',
    authorityInvolved: false,
    decisionNotes: 'Accepted by CCB; test harness will be available within 2 weeks.',
  },
  {
    dwId: 'DW-011',
    type: 'Deviation',
    title: 'Deviation from ICD timing for legacy actuator',
    linkedCIs: ['CI-INT-003'],
    riskLevel: 'Medium',
    validUntil: null,
    status: 'Submitted',
    authorityInvolved: true,
    decisionNotes: '',
  },
]

export const MOCK_AUDIT_EVENTS: AuditEvent[] = [
  {
    eventId: 'EV-101',
    timestamp: iso(new Date(now.getTime() - 1 * 60 * 60 * 1000)),
    actor: 'A. Lee',
    action: 'UPDATE_CI',
    objectRef: 'CI-SW-002',
    details: 'Version updated to 1.4.0',
  },
  {
    eventId: 'EV-100',
    timestamp: iso(new Date(now.getTime() - 2 * 60 * 60 * 1000)),
    actor: 'K. Park',
    action: 'SUBMIT_CR',
    objectRef: 'CR-045',
    details: 'Change request submitted for review',
  },
  {
    eventId: 'EV-099',
    timestamp: iso(new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000)),
    actor: 'L. Davis',
    action: 'APPROVE_RELEASE',
    objectRef: 'REL-2026.04',
    details: 'Release approved for internal delivery',
  },
  {
    eventId: 'EV-098',
    timestamp: iso(new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000)),
    actor: 'L. Davis',
    action: 'APPROVE_CR',
    objectRef: 'CR-044',
    details: 'CR approved; version update to be applied',
  },
  {
    eventId: 'EV-097',
    timestamp: iso(new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000)),
    actor: 'L. Davis',
    action: 'APPROVE_BASELINE',
    objectRef: 'BL-2026-03-PDR',
    details: 'PDR baseline approved',
  },
  {
    eventId: 'EV-096',
    timestamp: iso(new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000)),
    actor: 'J. Smith',
    action: 'FREEZE_BASELINE',
    objectRef: 'BL-2026-03-PDR',
    details: 'PDR baseline frozen',
  },
]
